### ISSUE TITLE
Docs - wording of build instructions in ReadMe

### ISSUE THREAD

**Issue by ardhill** [htop-dev/htop#92] opened 2020-09-03 14:45 UTC
[![htop3-installation-readme.png](https://i.postimg.cc/JnVxczt7/htop3-installation-readme.png)](https://postimg.cc/cKhfdZQP)

 <br />  

Your docs say:

> Build instructions
> 
> This program is distributed as a standard autotools-based package. For detailed instructions see the INSTALL file, which is created after ./autogen.sh is run.
> 
> When compiling from a release tarball, run:
> 
> ./configure && make

But, when you go to the link for the release tarball (https://github.com/htop-dev/htop/releases/) download and extract. There is no configure, but there is a autogen.sh. So you can't actually `./configure && make`, you need to run autogen.sh first.  

[![htop3-ls.png](https://i.postimg.cc/50b7WtJ7/htop3-ls.png)](https://postimg.cc/NyC71B5m)

<br />  

I would clone, change the readme.md and request a pull request, but it would be more hassle for you than to just make a basic change to the ReadMe file. Though, if you want me to do that, please just say. I am happy to do so.

**Comment by BenBE** [comment] 2020-09-07 07:28
Related to #31 maybe?
Duplicate of #60.

**Comment by fasterit** [comment] 2020-10-05 20:32
Resolved in https://github.com/htop-dev/htop/commit/3a1c6985789426a2bfc9c7d39eb66c143c6a1c7e

**Closed by fasterit** 2020-10-05 20:32 UTC
