### ISSUE TITLE
Process tree, branch connectors look inverted when sorted reversed by start time

### ISSUE THREAD

**Issue by cherio** [htop-dev/htop#393] opened 2020-12-13 02:47 UTC
```
$ htop --version
htop 3.0.3
```

Package as installed: [htop_3.0.3-1+b1_amd64.deb](https://packages.debian.org/bullseye/amd64/htop/download)

To reproduce:
1. Switch to "process tree" presentation
2. If missing add process start time field
3. Sort by the start time field
4. Sort by the start time field in reverse

The odd looking tree connectors are circled in red on the attached screenshot

![image](https://user-images.githubusercontent.com/2200569/102001705-0380e400-3cc3-11eb-8e48-7c3b22e807dd.png)

This is definitely a low priority bug

**Comment by fasterit** [comment] 2020-12-13 08:00
Already fixed in 4c44a70f96d1cc826d5388bea33d542273d066af and in htop_3.0.3-2 in Debian
Duplicate of #375

**Closed by fasterit** 2020-12-13 08:00 UTC
