### ISSUE TITLE
Crash while sorting on a column

### ISSUE THREAD

**Issue by r-l8** [htop-dev/htop#244] opened 2020-10-11 12:16 UTC
I encountered a crash while using htop. It occurred after I added the cgroup column to the main display then clicked on on of the column headers to sort. Not certain which column as the click was unintentional.

Backtrace
```
htop 2.1.0 aborting. Please report bug at http://hisham.hm/htop

 Please include in your report the following backtrace:
htop(CRT_handleSIGSEGV+0x33)[0x7f15fbe1f383]
/lib/x86_64-linux-gnu/libc.so.6(+0x3efd0)[0x7f15fae3efd0]
htop(+0xc37b)[0x7f15fbe0c37b]
htop(ScreenManager_run+0x277)[0x7f15fbe150f7]
htop(+0x19e9b)[0x7f15fbe19e9b]
htop(+0xe2c6)[0x7f15fbe0e2c6]
htop(ScreenManager_run+0x277)[0x7f15fbe150f7]
htop(main+0x3f1)[0x7f15fbe0ba21]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f15fae21b97]
htop(_start+0x2a)[0x7f15fbe0bc4a]

Additionally, in order to make the above backtrace useful,
please also run the following command to generate a disassembly of your binary:

   objdump -d `which htop` > ~/htop.objdump

and then attach the file ~/htop.objdump to your bug report.

Thank you for helping to improve htop!
```

lsb_release -a
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

uname -a
```
Linux Laptop28 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Edit: disassembly attached.

[htop.zip](https://github.com/htop-dev/htop/files/5361036/htop.zip)

**Comment by BenBE** [comment] 2020-10-11 12:30
Looks similar to #191. Please recheck with a more recent version of htop (e.g. from master or latest release).

**Comment by r-l8** [comment] 2020-10-11 14:11
Agreed, the backtraces are identical modulo virtual memory mapping. Sorry for the duplicate. I couldn't reproduce it either. Feel free to close this issue. Great program BTW, thank you for the effort!

**Comment by fasterit** [comment] 2020-10-11 15:13
Duplicate of #191.
Closed on request of @r-l8 and @BenBE.

**Closed by fasterit** 2020-10-11 15:13 UTC
