### ISSUE TITLE
segfault when closing htop multiple instances are open and conf. is changed on one

### ISSUE THREAD

**Issue by KaeLL** [htop-dev/htop#869] opened 2021-11-09 18:12 UTC
htop 3.1.1 on Clear Linux
1. Open 2 instances of htop
2. Change toggle tree view setting on the first
3. F10
4. Quit the 2nd instance
5. Quit the 1st instance
6. Get a segfault and exit code 139 from quitting 1st instance

**Comment by fasterit** [comment] 2021-11-09 20:25
This could be a duplicate of #844. Can you try the fix from https://github.com/htop-dev/htop/commit/604744f68d5c0375987eb9b60298f2affd1d8f38?

**Comment by xse** [comment] 2021-11-22 22:38
Hello, experienced the same issue on 3.1.
![YrNcjf8](https://user-images.githubusercontent.com/183953/142945319-bcef82f6-0d57-49b0-9654-4888578cb5bb.png)
1

Building against today's git version (3.1.1-20-g1284ab4) fixes that issue.
Have a good day o/

**Comment by BenBE** [comment] 2021-11-22 23:29
Thanks for confirming this to be a duplicate of the issue @fasterit suspected.

Closing this as a fix for the issue has already been merged in the main development branch.

**Closed by BenBE** 2021-11-22 23:29 UTC
Labels: bug :bug:, duplicate :do_not_litter:
