### ISSUE TITLE
htop v3.3.0 always displays "0 running"

### ISSUE THREAD

**Issue by yganwork** [htop-dev/htop#1418] opened 2024-03-18 09:26 UTC
I have several machines running Rocky linux 9.3 and htop v3.3.0 (currently latest).  When running htop, it always displays "0 running", even if I have dozens of processes displaying "R" in the "S" column.  On a machine running Rocky linux 8.9 and htop v3.2.1, the display is correct.  Just wanted to report this, thank you for this very useful tool!

**Comment by fasterit** [comment] 2024-03-18 10:31
Duplicate of #1369 , fixed in b6b9384

**Closed by fasterit** 2024-03-18 10:31 UTC

**Comment by yganwork** [comment] 2024-03-18 10:47
Thank you for this very fast response. I will wait until this is packaged for my linux distribution (EPEL repository). Sorry for the inconvenience.
