### ISSUE TITLE
Show the CPU and RAM usage per binary

### ISSUE THREAD

**Issue by FranklinYu** [htop-dev/htop#1258] opened 2023-06-08 00:13 UTC
This is a feature request.

The requirement is described in [this Unix.SE question](https://unix.stackexchange.com/questions/209689/sum-the-memory-usages-of-all-the-processes-of-a-program). In other words, it would be nice to group the RAM and CPU usage by binary for multi-process applications, such as Chrome.

An answer below mentioned `atop`, which works for me, but I’m used to the interactive features of `htop`.

**Comment by FranklinYu** [comment] 2023-06-08 00:25
Another idea is that, in the tree view, optionally show the total CPU and RAM when a node is collapsed. This idea was mentioned in https://superuser.com/questions/866007/memory-usage-grouped-by-parent-process.

**Comment by fasterit** [comment] 2023-06-08 06:13
Duplicate of #301

**Closed by fasterit** 2023-06-08 06:13 UTC
Labels: duplicate :do_not_litter:

**Comment by FranklinYu** [comment] 2023-06-20 01:11
Thanks. After reading #301 and #1154, I decided that #1154 might works better for me, as it covers more edge-cases, such as child processes with different binaries. I’ll follow #1154 instead.
