### ISSUE TITLE
Feature request: provide bona-fide source tarballs (minted using "make dist")

### ISSUE THREAD

**Issue by shlomif** [htop-dev/htop#45] opened 2020-08-30 13:28 UTC
Hi!

See: https://github.com/shlomif/plea-to-not-use-github-tags-as-releases/blob/master/article.md . One can attach them to the GitHub's tag. Thanks for maintaining htop!

**Comment by Ckath** [comment] 2020-08-30 22:09
duplicate of #31?

**Comment by natoscott** [comment] 2020-08-31 05:55
I've created: https://bintray.com/htop/source/htop
and there's direct tarball links at https://dl.bintray.com/htop/source/

**Closed by natoscott** 2020-08-31 05:55 UTC

**Comment by shlomif** [comment] 2020-08-31 06:32
On Sun, 30 Aug 2020 22:55:43 -0700
Nathan Scott <notifications@github.com> wrote:

> I've created: https://bintray.com/htop/source/htop
> and there's direct tarball links at https://dl.bintray.com/htop/source/
> 

Thanks for handling it so quickly. Note however that the tarball link there has
a colon right before the tar.gz basename.

-- 

Shlomi Fish       https://www.shlomifish.org/
List of Portability Libraries - https://shlom.in/port-libs

Because you can't just make shit up and expect the computer to magically know
what you mean, Retardo!
    — Mark Jason Dominus, https://perl.plover.com/Questions4.html

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by natoscott** [comment] 2020-09-01 00:00
@shlomif thanks, I've reported the issue to bintray.com
