### ISSUE TITLE
AIX support

### ISSUE THREAD

**Issue by lm8** [htop-dev/htop#868] opened 2021-11-05 21:24 UTC
Tried building htop on AIX and it builds with some patching.  However, it says platform unsupported and does not appear to show much.  Saw this post on an older version of htop:
https://github.com/hishamhm/htop/issues/831  The post lists similar patches to what I've done.  However, the screenshot is showing processes and tasks and I didn't noticed any when I tried to run what I built.  Is there a supported platform with similar functionality that I can use with AIX or any tips on where to start to possibly add support for AIX to what I'm running?  Thanks.

**Comment by BenBE** [comment] 2021-11-05 22:13
Duplicate of #584 … Note in particular [this comment](https://github.com/htop-dev/htop/issues/584#issuecomment-821296962).

**Closed by BenBE** 2021-11-05 22:13 UTC
Labels: wontfix, new feature
