### ISSUE TITLE
show program path should not affect kernel threads

### ISSUE THREAD

**Issue by xuefer** [htop-dev/htop#1523] opened 2024-08-16 04:54 UTC
Uncheck both
- [ ] Hide kernel threads
- [ ] Show program path

Version: htop 3.3.0

most kernel threads is shown as numeric 0 1 2 etc.  it was something like ```ksoftirqd/0``` ```ksoftirqd/1``` etc. i don't think it's anything like path, even if it is, leaving numeric "basename" is hard to read

**Comment by cgzones** [comment] 2024-08-24 18:56
Duplicate of #1391 fixed via https://github.com/htop-dev/htop/commit/32cb30273b9785ba2dd2cada5d0a677f97db7ec0.

**Closed by cgzones** 2024-08-24 18:56 UTC
Labels: enhancement, Linux :penguin:
