### ISSUE TITLE
Strange doubling-up of Command info

### ISSUE THREAD

**Issue by vaskark** [htop-dev/htop#903] opened 2021-12-22 18:10 UTC
I'm using a fully updated htop from git and this is the result:

[external link](https://imgur.com/acQHEuE)
![image](https://user-images.githubusercontent.com/111196/147138931-c8aa1884-279e-4318-a13b-abd41076ebe5.png)

It's been happening for a few weeks. Any advice?
I'm on Ubuntu 21.10.

Thanks.

**Comment by BenBE** [comment] 2021-12-22 18:38
Can you please provide the following details for debugging?

1. Contents of your `htoprc`
2. Exact commit hash you built
3. What do the `EXE` and `COMM` columns for this look like?
4. Any previous version (e.g. release tag) where things were still okay?
5. Can you try a `git bisect` between the current version and the last known good, to isolate the issue down to a certain change?

Does activating/deactivating merged command lines (pressing <kbd>m</kbd>) have an effect on this?

One guess I have might be with the `htoprc` being somewhat broken. From the screenshot it looks like `Command` is not the last column, but the `COMM` column.

**Comment by vaskark** [comment] 2021-12-22 18:52
Thanks for replying so quickly.
I looked at my htoprc and took out the COMM column (the interface wouldn't let me for some reason). It looks okay now.
Would you still like me to answer the rest of all your questions? Will it be useful to you guys?

**Comment by BenBE** [comment] 2021-12-22 18:58
Okay, given that this really was the issue, it might be great to know how this was caused in the first place. If you did some upgrading in the past few weeks, this could be a start for steps to reproduce this. One major change we had recently was the introduction of screen tabs, thus the conversion of the configuration file with that upgrade could be the cause for this artifact.

No need to answer the further questions, but I'd be glad if you could check if this behaviour is somehow reproducible. TIA.

**Comment by BenBE** [comment] 2021-12-23 00:26
Note by @cgzones on IRC hinting at https://github.com/htop-dev/htop/commit/5bc988ad6de7d0767c639fb150e68be78c00b1fa as the bugfix for an issue introduced with the multi-screen feature.

**Comment by vaskark** [comment] 2021-12-24 17:16
I haven't been able to reproduce the bug I encountered. I even put my old htoprc into use from my dotfiles archive. The problem didn't show up again.

**Comment by BenBE** [comment] 2021-12-24 22:58
Good to know. I'd suggest marking this as closed for now. If there's some new things for this subject feel free to reopen.

**Closed by BenBE** 2021-12-24 22:58 UTC
Labels: bug :bug:, question :grey_question:
