### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by ioogithub** [htop-dev/htop#949] opened 2022-02-27 02:03 UTC
When I press F2, set everything up properly and press F10 a file is written here:
/home/user/.config/htop/htoprc

This is the file:
```
# Beware! This file is rewritten by htop when settings are changed in the interface.
# The parser is also very primitive, and not human-friendly.
fields=0 48 17 18 38 39 40 2 46 47 49 1
sort_key=46
sort_direction=1
hide_threads=0
hide_kernel_threads=1
hide_userland_threads=0
shadow_other_users=0
show_thread_names=0
show_program_path=1
highlight_base_name=0
highlight_megabytes=1
highlight_threads=1
tree_view=0
header_margin=1
detailed_cpu_time=0
cpu_count_from_zero=0
update_process_names=0
account_guest_in_cpu_meter=0
color_scheme=0
delay=15
left_meters=
left_meter_modes=
right_meters=
right_meter_modes=
```

None of my settings are actually saved. This same file is written out no matter what settings I have selected.

Version:
htop 2.2.0 - (C) 2004-2019 Hisham Muhammad
Released under the GNU GPL.

System:
KDE Neon 5.24

**Comment by BenBE** [comment] 2022-02-27 20:21
The version you're using is quite old. Please re-test if this issue persists with a more recent version.

That aside: Please also check the user you are running `htop` with actually has write permissions on the file and its containing folder.

**Comment by winslowb** [comment] 2022-09-07 21:47
I have the same issue on 3.0.5.

**Comment by winslowb** [comment] 2022-09-07 21:50
I manually updated  htopprc and my config saved.

**Comment by jifbrodeur** [comment] 2022-11-02 12:53
Hi, running 3.2.1 on macOS same issue:
Warning: htop 3.2.1 is already installed and up-to-date.
htop
Can not save configuration to /Users/jif/.config/htop/htoprc: Permission denied
looking at the permission, I see that the owner of the ~/.config/htop is root, shall I change it,
drwx------     - root  3 Oct 14:13  htop/
 I did a normal brew install?
Thanks
Jean-François

**Comment by BenBE** [comment] 2022-11-02 16:24
You must be allowed to read and write the configuration with the user htop executes as if you want to be able to save the configuration.

**Comment by cgzones** [comment] 2022-11-02 19:41
Seems like a duplicate of #1092; see https://github.com/htop-dev/htop/issues/1092#issuecomment-1252762609 for solutions.

**Comment by jifbrodeur** [comment] 2022-11-03 12:37
Hi and Thanks for your answer but it seems to me as if the brew install is not setting the ownership of the ~/.config/htop correctly, I installed it as user jif, but when removing and re-installing htop as jif, it creates the configuration directory and set its owner to root under jif home directory which I think is wrong. Changing the owner to jif resolves the issue but may I ask that the brew install properly set the owner ship of the configuration directory to the user running the installation?
Thanks
Jean-François

**Comment by BenBE** [comment] 2022-11-03 12:59
> Changing the owner to jif resolves the issue but may I ask that the brew install properly set the owner ship of the configuration directory to the user running the installation?
> Thanks
> Jean-François

We are not responsible for packaging things for brew, thus please forward this issue to @cho-m who seems to be maintaining the brew based on https://formulae.brew.sh/formula/htop and https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/htop.rb

**Comment by jifbrodeur** [comment] 2022-11-04 12:46
Thanks for listening, this is what I will do. On my m1 mac this did not happen...

**Comment by jcbritobr** [comment] 2023-07-06 11:01
It happens in fedora linux 38

**Comment by BenBE** [comment] 2023-07-06 11:32
> It happens in fedora linux 38

What happens? What you're doing? Did you read about the [required permissions](https://github.com/htop-dev/htop/issues/949#issuecomment-1300824675) and you also acknowledged that the configuration is only stored upon successful termination (and not if hitting Ctrl+c)?

**Comment by jcbritobr** [comment] 2023-07-06 11:36
> > It happens in fedora linux 38
> 
> What happens? What you're doing? Did you read about the [required permissions](https://github.com/htop-dev/htop/issues/949#issuecomment-1300824675) and you also acknowledged that the configuration is only stored upon successful termination (and not if hitting Ctrl+c)?

Yes, but wasn't a permission issue. ctrl+c was the issue here. Thank you.

**Comment by ykla** [comment] 2023-08-08 05:32
Not work in freebsd 14. htop-3.2.2_1

And must setting  ~/.config/htop/htoprc  by hand.

**Comment by BenBE** [comment] 2023-08-08 07:48
Have you checked for proper permissions AND ownership of the `htoprc` config file and its parent directories?

Also: After changing the setting you need to _exit `htop` normally by pressing <kbd>F10</kbd>_ or <kbd>q</kbd>.

Exiting `htop` by **pressing <kbd>Ctrl</kbd>+<kbd>c</kbd> will discard any unsaved changes**. This is intentional.

**Comment by ykla** [comment] 2023-08-08 14:16
> Have you checked for proper permissions AND ownership of the `htoprc` config file and its parent directories?
> 
> Also: After changing the setting you need to _exit `htop` normally by pressing F10_ or q.
> 
> Exiting `htop` by **pressing Ctrl+c will discard any unsaved changes**. This is intentional.

Well, then everything is running fine.

**Closed** 2023-08-08 15:13 UTC
Labels: support request, MacOS :green_apple:

**Comment by veita** [comment] 2023-12-09 18:41
On Fedora Server 39 `/root/.config/` and thus `/root/.config/htop/` is missing after htop is being installed. As a consequence htop`s settings are not persisted. Manually creating `mkdir -p .config/htop` is a workaround for the problem.

**Comment by Gelias212** [comment] 2025-06-30 04:07
reviving this old issue but mine wasn't saving, so I manually created the empty htoprc file in ~/.config/htop/ , ran htop changed some settings and bam, file created and settings saved. I'm on htop 3.4.1

**Comment by digin1** [comment] 2025-08-28 23:08
Can someone edit the title from

**Settings are not saved with Ctrl+c but works with q or F10. (edited)**

So other vistors would not have to waste time.
