### ISSUE TITLE
focus in/out causes process list to be temporarily unsorted

### ISSUE THREAD

**Issue by pobrn** [htop-dev/htop#1260] opened 2023-06-11 01:18 UTC
## Steps to reproduce

1. start a terminal emulator that sends XTERM focus in/out reports (e.g. `gnome-terminal`)
2. start `htop`
3. select the process list view and sort by e.g. CPU usage
4. focus a different window

## Actual behaviour

Observe that process list will not be sorted for the next 4 updates.

## Expected behaviour

The process list continues to be sorted.

## Cause

This is because VTE (that `gnome-terminal` uses) sends XTERM focus in/out reports (588 and 589 as returned by `Panel_getCh()`, respectively), and those are handled in the default branch of switch case at `ScreenManager.c:412`, [where `sortTimeout` is set to 5](https://github.com/htop-dev/htop/blob/d8fe027875427be6f5e598fc82373ecb5ed84859/ScreenManager.c#L414).

More info about these "keys": https://github.com/vim/vim/blob/10e8ff9b26078994cae57c2422b145d37aaf714e/src/term.c#L2220

**Comment by russelltg** [comment] 2023-06-13 21:07
I think I'm running into this issue--i'm not 100% what triggers it but definitely running into an issue where sort is incorrect for several seconds (but then it recovers--in this video I force a resort with `t` `t`)

https://github.com/htop-dev/htop/assets/7105082/96c3ce52-13da-4f74-b47f-b046637b4a79

**Comment by SnipeXandrej** [comment] 2023-06-17 15:14
I am seeing the exact same behavior on Konsole.

**Comment by BenBE** [comment] 2023-07-19 11:29
> In sway htop window becoming focused causes the sorting direction to change. So by repeatedly moving cursor in and out of the window in can change sort direction up and down. Direction does NOT reset after some updates.

If the focus change modifies the sorting direction in htop you should check your terminal for the proper key mapping. On a low level there's not much that can be done when the key codes are mapped incorrectly by your terminal.

**Comment by pakettiale** [comment] 2023-07-20 13:24
> If the focus change modifies the sorting direction in htop you should check your terminal for the proper key mapping. On a low level there's not much that can be done when the key codes are mapped incorrectly by your terminal.

Looks like ncurses broke the terminfo file that I'm using.

**Comment by OmarElfouly** [comment] 2024-10-09 09:27
Hello @BenBE !
I m new to contributing to open source and I m interested in contributing to this project by figuring this out but I'm unclear of whether the final decision was to treat this as intended behavior or not:

> There is a feature in htop that disables sorting, when an input is made. This is in order to allow properly selecting a process even on somewhat busy systems.

Also I was hoping for advice on where to start to hunt down possible causes and their solutions.

**Comment by BenBE** [comment] 2024-10-09 09:46
The conclusion was along the lines of that the change of sort order experienced by some is a bug in the terminfo database used. Handling the focus in/out events and processing them as input is not by itself wrong, but could be done to skip the sort order freeze if these events are recognized.

You can find details of where you need to look and what roughtly needs to be added in the initial report at the top. Also there's a list of special key sequences recognized by htop in `CRT.c`.

**Comment by OmarElfouly** [comment] 2024-10-10 09:33
Thank you for your replies!

> Something changed because for some time now `htop` hasn't reacted this way to focus changes. But I am not sure if it was `vte` or `htop`.

I agree as I was unable to replicate it anymore using gnome terminal in Ubuntu 24.04.1 LTS. Does this mean this issue has been resolved?

**Comment by BenBE** [comment] 2024-10-11 18:16
At least nothing that I am aware off OTOH. Closing it for now; can be re-opened if there is new need.

**Closed by BenBE** 2024-10-11 18:16 UTC
Labels: enhancement, good first issue :1st_place_medal:, Hacktoberfest
