### ISSUE TITLE
FreeBSD:  Chromium, Widevine, htop: kernel panic: condition vp->v_type == VDIR || VN_IS_DOOMED(vp) not met ⋯vfs_cache.c:3452 (vn_fullpath_dir)

### ISSUE THREAD

**Issue by grahamperrin** [htop-dev/htop#1537] opened 2024-09-14 04:46 UTC
Please: might this system crash be fixable, or avoidable, in htop?

In a nutshell: 

- FreeBSD-CURRENT `GENERIC` panics immediately with combined use of Widevine and htop
  - <https://bitmovin.com/demos/drm> is a suitable test, if Widevine is detected
  - not reproducible with the `GENERIC-NODEBUG` kernel
- <https://lists.freebsd.org/archives/freebsd-current/2024-May/005980.html> (2024-05-22)
- no response to [Widevine: kernel panics (system crashes) with Chromium : freebsd](https://old.reddit.com/r/freebsd/comments/1d19zez/widevine_kernel_panics_system_crashes_with/) (Reddit, 2024-05-24)
  - there's a copy of my 2024-05-27 email to the maintainer of [sysutils/htop](https://www.freshports.org/sysutils/htop/) (the port to FreeBSD)
- thread [Chromium, Widevine (DRM), htop: kernel panics](https://discord.com/channels/727023752348434432/1244482186728706100) (2024-05-24) in the `#desktop` channel of FreeBSD Discord was brief, nothing conclusive.

<https://codeberg.org/grahamperrin/freebsd-src/issues/10#issuecomment-2312310> summarises this morning's incident.

**Comment by BenBE** [comment] 2024-09-14 20:51
Can you isolate a call-site address within htop of where the offending syscall is triggered?

Doing a quick search in the FreeBSD-specific parts of the code, one possible location could be at
`freebsd/FreeBSDProcessTable.c` line 66+69. Can you check if there is any difference when you skip this syscall (e.g. return a string of the PID instead for testing).

You may also try to skip other syscalls in the `freebsd` sub-directory to narrow the issue down. Once the location has been narrowed down we can check if there is any sensible work-around from userland, or if the upstream kernel has to put mitigations in place.

**Comment by grahamperrin** [comment] 2024-09-15 16:11
Thank you, 

> … line 66+69. Can you check if there is any difference when you skip this syscall (e.g. return a string of the PID instead for testing). …

I see that range of lines, however (sorry) I have no idea what to do with them; I'm not a developer. 

I'll seek guidance in FreeBSD Discord …

**Comment by BenBE** [comment] 2024-09-16 06:47
You can try to replace that function by

```c
static void FreeBSDProcessTable_updateExe(const struct kinfo_proc* kproc, Process* proc) {
   if (Process_isKernelThread(proc)) {
      Process_updateExe(proc, NULL);
      return;
   }

   const int mib[] = { CTL_KERN, KERN_PROC, KERN_PROC_PATHNAME, kproc->ki_pid };
   char buffer[2048];
   xSnprintf(buffer, sizeof(buffer); "/proc/%d/exe", kproc->ki_pid);

   Process_updateExe(proc, buffer);
}
```

and recompile `htop`. Does this still show the kernel crash?

**Comment by grahamperrin** [comment] 2024-09-16 19:35
I'll try, thanks. 

Meantime, from <https://lists.freebsd.org/archives/freebsd-current/2024-September/006411.html>: 

> … As far as I can see, htop touches the problem area but itself is not the problem. The handling of the "worker" related context for the type of kernel call seems to be what is at issue, likely no matter what process happens to make the same basic kernel call that ends up with "worker" in the context.
> 
> ===
> Mark Millard

**Comment by grahamperrin** [comment] 2024-09-16 19:44
```text
…
depbase=`echo freebsd/FreeBSDProcessTable.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; gcc -DHAVE_CONFIG_H -I.  -DNDEBUG   -std=c99 -pedantic -Wall -Wcast-align -Wcast-qual -Wextra -Wfloat-equal -Wformat=2 -Winit-self -Wmissing-format-attribute -Wmissing-noreturn -Wmissing-prototypes -Wpointer-arith -Wshadow -Wstrict-prototypes -Wundef -Wunused -Wwrite-strings -Wnull-dereference -D_XOPEN_SOURCE_EXTENDED  -DSYSCONFDIR="\"/usr/local/etc\""  -I"./freebsd" -g -O2 -MT freebsd/FreeBSDProcessTable.o -MD -MP -MF $depbase.Tpo -c -o freebsd/FreeBSDProcessTable.o freebsd/FreeBSDProcessTable.c && mv -f $depbase.Tpo $depbase.Po
freebsd/FreeBSDProcessTable.c: In function 'FreeBSDProcessTable_updateExe':
freebsd/FreeBSDProcessTable.c:68:36: error: expected ')' before ';' token
   68 |    xSnprintf(buffer, sizeof(buffer); "/proc/%d/exe", kproc->ki_pid);
      |             ~                      ^
      |                                    )
freebsd/FreeBSDProcessTable.c:68:4: error: too few arguments to function 'xSnprintf'
   68 |    xSnprintf(buffer, sizeof(buffer); "/proc/%d/exe", kproc->ki_pid);
      |    ^~~~~~~~~
In file included from ./HeaderLayout.h:15,
                 from ./Settings.h:15,
                 from ./CRT.h:14,
                 from ./Panel.h:13,
                 from ./Machine.h:17,
                 from ./ProcessTable.h:14,
                 from ./freebsd/FreeBSDProcessTable.h:14,
                 from freebsd/FreeBSDProcessTable.c:10:
./XUtils.h:108:5: note: declared here
  108 | int xSnprintf(char* buf, size_t len, const char* fmt, ...);
      |     ^~~~~~~~~
freebsd/FreeBSDProcessTable.c:66:14: warning: unused variable 'mib' [-Wunused-variable]
   66 |    const int mib[] = { CTL_KERN, KERN_PROC, KERN_PROC_PATHNAME, kproc->ki_pid };
      |              ^~~
*** Error code 1

Stop.
make[1]: stopped making "all-am" in /usr/home/grahamperrin/dev/htop
*** Error code 1

Stop.
make: stopped making "all" in /usr/home/grahamperrin/dev/htop
% 
```
![image](https://github.com/user-attachments/assets/b47f610c-3660-4735-b73c-3a9ff5f622ea)

**Comment by BenBE** [comment] 2024-09-16 20:11
Typo in the code block. That `;` should have been a `,` …

**Comment by grahamperrin** [comment] 2024-09-17 00:35
<https://github.com/htop-dev/htop/issues/1537#issuecomment-2352127364>

> … and recompile `htop`. Does this still show the kernel crash?

No kernel panic. Thank you!

```text
% ~/dev/htop/htop
% uname -v
FreeBSD 15.0-CURRENT main-n272256-1c6bb4c5789c GENERIC
% pkg iinfo www/chromium www/foreign-cdm www/linux-widevine-cdm
chromium-128.0.6613.119_1
foreign-cdm-20231217_3
linux-widevine-cdm-4.10.2710.0
% 
```

**Comment by grahamperrin** [comment] 2024-09-17 07:08
<https://lists.freebsd.org/archives/freebsd-current/2024-September/006418.html> big thanks to Mark Millard for investigating on the FreeBSD side, and big thanks to @BenBE for the workaround.

**Comment by BenBE** [comment] 2024-09-17 07:14
Marking as WontFix, as the core issue is outside our control and the only reasonable workaround would be a hard regression with unjustified impact on unaffected users.

**Closed** 2024-09-17 07:17 UTC
Labels: wontfix, support request, FreeBSD :japanese_ogre:

**Comment by Explorer09** [comment] 2024-09-17 14:59
Does this affect any stable version of the FreeBSD kernel, or is it only development version that is affected?
Since this is a kernel panic, it is better to give a reasonable warning for users who run htop on affected kernels.

**Comment by grahamperrin** [comment] 2024-11-07 00:57
<https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=282596>
