### ISSUE TITLE
Bug: [F2] Setup: settings not saved/persistant

### ISSUE THREAD

**Issue by zWhdmB5T** [htop-dev/htop#1318] opened 2023-10-21 10:06 UTC
### my system:
* `OS: openSUSE Leap 15.5 x86_64`
* `htop 3.2.2`

### bug:
1. start htop
2. using [F2] Setup
3. making some changes
4. using [F10] Done
5. using htop
6. exit htop
7. (re-)start htop
*  settings not persistant

### notices:
* there is the directory `~/.config/htop/` with `drwx------` (user) present, but no config file inside

**Comment by zWhdmB5T** [comment] 2023-10-21 10:26
# addition:
I just noticed, this behaviour stated above only occurs when I start htop by the GUI menu (Xfce)
![Bildschirmfoto_2023-10-21_12-24-30](https://github.com/htop-dev/htop/assets/143814533/478f2746-8a87-4066-896a-59de2c557df1)
. This is the usual way here, so far. But when I start a terminal separately and then start htop explicitly, it works fine (change settings and storing settings). When I then start htop by the GUI, settings (like made before) are read and used. But I cannot persistently change them.

**Comment by BenBE** [comment] 2023-10-21 12:19
This looks strange.

Can you check the following:
- Use <kbd>Shift</kbd>+<kbd>S</kbd> instead of <kbd>F2</kbd>
- Use <kbd>Q</kbd> instead of <kbd>F10</kbd>
- What is the user shown for the `htop` process?
- What are the owner and permissions for `~/.config`, `~/.config/htop` and `~/.config/htop/htoprc`?
- What is your active (default) `umask`?

In addition:
- Which OS/Distro?
- If you start `htop` from a terminal, are the settings persisted (e.g. change sort order)? What does the created `~/.config/htop/htoprc` look like?

**Comment by zWhdmB5T** [comment] 2023-10-21 13:14
>     * Use Shift+S instead of F2
shows the screen of  `[F2]`
 
>     * Use Q instead of F10
closes the screen of `[F2]` — but: changes are not persistent!

>     * What is the user shown for the `htop` process?
I did `[F4]` and searched for `htop`: the relating user is my user `gunnersson`

>     * What are the owner and permissions for `~/.config`, `~/.config/htop` and `~/.config/htop/htoprc`?
`drwx------ 42 gunnersson users 4,0K 21. Okt 11:52 .config/`
`drwx------  2 gunnersson users 4,0K 21. Okt 12:09 htop/`
`-rw-------  1 gunnersson users 1,7K 21. Okt 12:17 htoprc`
 
>     * What is your active (default) `umask`?
`gunnersson@tulicube:~> umask` 
`0077`

> In addition:
> 
>     * Which OS/Distro?
`OS: openSUSE Leap 15.5 x86_64`
`Kernel: 5.14.21-150500.55.31-default`
 
>     * If you start `htop` from a terminal, are the settings persisted (e.g. change sort order)? What does the created `~/.config/htop/htoprc` look like?
to make it clear again: when I start `htop` from GUI (Xfce), changes are not saved, get lost. when I start `htop` from separate terminal explicitly, changes are saved, are persistent.
`~/.config/htop/htoprc` :
[htoprc.txt](https://github.com/htop-dev/htop/files/13060762/htoprc.txt)
( extension `TXT` because of file filter of GitHub)

**Comment by BenBE** [comment] 2023-10-21 15:33
> > ```
> > * Use Shift+S instead of F2
> > ```
> 
> shows the screen of `[F2]`
> 
> > ```
> > * Use Q instead of F10
> > ```
> 
> closes the screen of `[F2]` — but: changes are not persistent!
> 

Tested for checking if mappings could be broken.

> > ```
> > * What is the user shown for the `htop` process?
> > ```
> 
> I did `[F4]` and searched for `htop`: the relating user is my user `gunnersson`
> 

That's the same for both on console and via the GUI?

> > ```
> > * What are the owner and permissions for `~/.config`, `~/.config/htop` and `~/.config/htop/htoprc`?
> > ```
> 
> `drwx------ 42 gunnersson users 4,0K 21. Okt 11:52 .config/` `drwx------ 2 gunnersson users 4,0K 21. Okt 12:09 htop/` `-rw------- 1 gunnersson users 1,7K 21. Okt 12:17 htoprc`
> 

Looks good.

> > ```
> > * What is your active (default) `umask`?
> > ```
> 
> `gunnersson@tulicube:~> umask` `0077`
> 

Shouldn't cause conflicts. But trying `umask 0002` might be worth a try.

> > In addition:
> > ```
> > * Which OS/Distro?
> > ```
> 
> `OS: openSUSE Leap 15.5 x86_64` `Kernel: 5.14.21-150500.55.31-default`
> 

Should be fine.

> > ```
> > * If you start `htop` from a terminal, are the settings persisted (e.g. change sort order)? What does the created `~/.config/htop/htoprc` look like?
> > ```
> 
> to make it clear again: when I start `htop` from GUI (Xfce), changes are not saved, get lost. when I start `htop` from separate terminal explicitly, changes are saved, are persistent. 

Are you sure, both cases start the same executable?

> `~/.config/htop/htoprc` : [htoprc.txt](https://github.com/htop-dev/htop/files/13060762/htoprc.txt) ( extension `TXT` because of file filter of GitHub)

Looks fine from its contents. Note that older versions of htop do not support this config file format. Thus if you happen to have an older version of htop it might cause this configuration file to be reset.

**Comment by zWhdmB5T** [comment] 2023-10-21 16:15
> > > ```
> > > * What is the user shown for the `htop` process?
> > > ```
> > 
> > 
> > I did `[F4]` and searched for `htop`: the relating user is my user `gunnersson`
> 
> That's the same for both on console and via the GUI?
> 
> > > ```
> > > * If you start `htop` from a terminal, are the settings persisted (e.g. change sort order)? What does the created `~/.config/htop/htoprc` look like?
> > > ```
> > 
> > 
> > to make it clear again: when I start `htop` from GUI (Xfce), changes are not saved, get lost. when I start `htop` from separate terminal explicitly, changes are saved, are persistent.
> 
> Are you sure, both cases start the same executable?
> 

Well, not exactly…

1. start `xfce-terminal`, then start `htop`
![Bildschirmfoto_2023-10-21_18-13-35](https://github.com/htop-dev/htop/assets/143814533/7afe6586-7387-4301-9d45-85900ef76b7b)

2. start `htop` from GUI
![Bildschirmfoto_2023-10-21_18-14-08](https://github.com/htop-dev/htop/assets/143814533/e3116a46-8db6-4dca-bd04-b763f621463e)

Well, yes, this looks quite different…

**Comment by zWhdmB5T** [comment] 2023-10-21 16:28
> > > ```
> > > * What is your active (default) `umask`?
> > > ```
> > 
> > 
> > `gunnersson@tulicube:~> umask` `0077`
> 
> Shouldn't cause conflicts. But trying `umask 0002` might be worth a try.
> 

I can state, that I personally changed `umask` to `0077`explicitly, one day in the past, due to security restrictions. Before, it was `0022` or `0027` (cannot remember exactly, any more).

I would rather not change this if not really necessary for its great impact. But maybe, this could really have an effect. My system in general works fine and properly and I don't expect any issues. Besides, when `zypper lr` in an `xfce-terminal` this does not work any more since `umask` change, I now need `sudo` or `su`.

**Comment by zWhdmB5T** [comment] 2023-10-21 16:55
addition: just tried `zypper lr`, it works (without `sudo` or `su`, just as expected — but it was different, some day)

**Comment by BenBE** [comment] 2023-10-21 22:19
Can you please redo those two screenshots with full program paths shown (<kbd>p</kbd>)?

@umask: Security implications known. Just a remark about any issues re file permissions when things are created and such and compat w/ htop.

Can you create a `strace` of the task tree when starting with the GUI?

**Comment by zWhdmB5T** [comment] 2023-10-22 09:44
> Can you please redo those two screenshots with full program paths shown (p)?

Well, those two screenshots did include full path names… If I press (p), then the path names are shortened. They are already in detail. Yes, obviously, the path for `xfce4-terminal` is shown, but not the path for `htop`.

**Comment by zWhdmB5T** [comment] 2023-10-22 09:49
> @umask: Security implications known. Just a remark about any issues re file permissions when things are created and such and compat w/ htop.

I am sorry, I don't understand this. Can you say it again, in other words, maybe.

**Comment by zWhdmB5T** [comment] 2023-10-22 09:54
> Can you create a `strace` of the task tree when starting with the GUI?

I tried to, but it was not successful. I opened another terminal and did `strace -p 15148`. <PID>=`15148` for the example above (in the screenshot), I did change it to the current one when running the example currently. But `strace` was running endlessly, it didn't stop automatically. What do I have to do?

**Comment by zWhdmB5T** [comment] 2023-10-22 10:05
For comparison:

To investigate and understand the output (resp. (full) path names) of `htop`), I do have running: `htop`, `atop`, `dstat`, `mc` (Midnight Commander), `mcedit` (Edit of Midnight Commander), `keepassxc` (KeepassXC, password safe program), `pinta` (Pinta, paint program). All started by using GUI starters.
Well, there might be more or less details in path names…
![Bildschirmfoto_2023-10-22_11-59-35](https://github.com/htop-dev/htop/assets/143814533/7f83630e-fcef-4304-ae18-55eaee3a5158)

**Comment by BenBE** [comment] 2023-10-22 13:18
> > @umask: Security implications known. Just a remark about any issues re file permissions when things are created and such and compat w/ htop.
> 
> I am sorry, I don't understand this. Can you say it again, in other words, maybe.

Let me phrase that differently:

I'm aware of the security implications of changing the `umask` for the system.
And my comment was just a note that this should not affect `htop`.

Regarding the `htop` executable in the screenshots: Can you check what the symlink `proc/<PID>/exe` points to when started in terminal vs. from GUI?

**Comment by zWhdmB5T** [comment] 2023-10-22 18:23
- terminal: `lrwxrwxrwx   1 gunnersson users 0 22. Okt 20:20 exe -> /usr/bin/htop*`
- GUI: `lrwxrwxrwx   1 gunnersson users 0 22. Okt 20:22 exe -> /usr/bin/htop*`

**Comment by fasterit** [comment] 2023-10-23 20:13
Cannot reproduce, ran openSUSE-Leap-15.5-XFCE-Live-x86_64-Build10.190-Media.iso in a qemu VM.
Saving htop settings worked both from the terminal and from the XFCE .desktop starter linked at Menu -> System -> Htop.
/DLange

```
linux@localhost:~> ll .config/htop/htoprc
-rw-r--r-- 1 linux users 1669 Oct 23 16:08 .config/htop/htoprc
# change a setting in the GUI-started htop, quit htop
linux@localhost:~> ll .config/htop/htoprc
-rw-r--r-- 1 linux users 1669 Oct 23 16:11 .config/htop/htoprc

```

**Comment by zWhdmB5T** [comment] 2023-10-23 20:29
@fasterit thank you for your testing effort! Because your result is obviously different than mine, I did some testing, too.

@BenBE and yes, it seems to be the `umask` setting… I temporarily set it to `0002` (as you suggested, above) and then the `[F2]` function works properly and fine. When you @BenBE say, it is as it is and no need for change on `htop`, then I have to make up my mind what `umask`setting I should use from now on. Any guess? Any helping notice on this very appreciated.

**Comment by zWhdmB5T** [comment] 2023-10-23 20:47
@BenBE sorry that I ping you, again. This is strange: since I _temporarily_ changed `umask` from `0077` to `0002` and then back to `0077` (and using `[F2]` in between), in `htop` the `[F2]` function seems to work properly and fine now — even with my regular `umask`. Do you remember, I told you about `zypper lr`: I had problems back in the past… it was only possible with `sudo` or `su`. Since some day and some change (I don't know the details), it works just like this. In any case, `umask` seems to have some specific effect on some objects, even if the user rights seem to be appropriate (we did check the user rights of `htop` above).

Well, I am a little bit confused… or it's a lack of Linux knowledge ;-)

**Comment by zWhdmB5T** [comment] 2023-10-23 22:50
It's me again, sorry.

I have to comment on my last post and correct something…

### `umask`
* I did temporarily change it to `0002`.
* I currently use `0077` regularly, again.

### quitting (exit) `htop`
* I noticed that I used `[F10]` to quit (exit) `htop` when I was doing the `umask` test and during the following tests right after — then settings are saved (and read)
* but usually (just not in the examples above) I use the `[X]` of the GUI window to quit (exit) — then settings are NOT saved
* to be more precise: (almost) whenever I use a GUI application (even like here: `htop` is started by GUI menu and runs in a terminal in a GUI window), I use the `[X]` of the GUI window to quit (exit)
* but when I started `htop` explicitly in a terminal, I  had to use `[F10]` — otherwise I would get a dialogue asking me to abort the GUI window (with the running terminal with `htop` inside)

### concluding question
* so, when are settings saved, actually?
* i.e. for the settings themself, I open the settings dialogue with `[F2]` and close it with `[F10]` — but has the program `htop`itself also to be closed by `[F10]` ? (remember, usually I would use the `[X]` of the GUI window when started by GUI)
*  I (personlly) would guess that settings are saved when closing the corresponding dialogue…

**Comment by zWhdmB5T** [comment] 2023-10-24 09:14
OK, then it was kind of misunderstanding / using it not the way intended from my side.

Ticket can be closed.

Sorry for all the circumstances.

**Comment by BenBE** [comment] 2023-10-24 11:38
The behaviour now got some documentation through commit 04c769c8. Further notes about this issue are currently discussed in #1319 regarding a special note when `htop` is terminated by a signal (although that unfortunately won't show up when exiting with the [X] button).

Closing here.

**Closed by BenBE** 2023-10-24 11:38 UTC
Labels: wontfix, support request
