### ISSUE TITLE
htop color 

### ISSUE THREAD

**Issue by djemilbakhti** [htop-dev/htop#1376] opened 2024-01-14 17:46 UTC
what mean this color on username 
![Screenshot_20240114_184543](https://github.com/htop-dev/htop/assets/39235831/a75738e4-58c6-44ae-bfe2-6b28c4a98874)

**Comment by BenBE** [comment] 2024-01-14 22:23
Please read the [fine manual](https://github.com/htop-dev/htop/blob/3.3.0/htop.1.in#L457-L460) that accompanies the release …

**Comment by Explorer09** [comment] 2024-01-15 09:21
It could be a bad usability if we convey important information with the color alone.

May I suggest adding a symbol after the username as an indicator? I think the "#" (hash) symbol is a good choice. (So the name would show as `bakhti#`.)

**Comment by fasterit** [comment] 2024-01-15 16:43
@Explorer09 Yes, you may suggest it but please not implement that. It does not make people read the manual more.

**Comment by Explorer09** [comment] 2024-01-15 19:39
@fasterit Why is it important for people to read the manual while the whole concept of "usability" is to free people's time from reading it?

It doesn't say that the manual is not important. The manual should be a last resort for the users, e.g. when something misbehaves, the user can look up the manual to see whether that's an expected behavior or a bug.

**Comment by fasterit** [comment] 2024-01-15 19:47
"#" is not a better usability than "highlight-color"

**Comment by Explorer09** [comment] 2024-01-15 19:55
@fasterit No, I mean to show both the symbol and the color. It could be useful if another highlight color is added to the username field in the future.

Since which highlight color would be used depends on the color scheme, you cannot write it would be colored "purple" in the manual. But the symbol would be fixed (i.e. not dependent on the color scheme). So it's easier to write that into the manual for reference.

**Comment by fasterit** [comment] 2024-01-15 20:15
Let's discuss this then "if another highlight color is added to the username field in the future"

**Comment by Explorer09** [comment] 2024-01-15 20:21
Oops. I have been using the wrong word for this. It's more about "accessibility". Especially for colorblind, or a monochrome terminal.

**Comment by fasterit** [comment] 2024-01-15 20:23
Improved accessibility (i.e. falling back from "<bold>text<normal>" to "text#") definitely make sense. This is a different topic though. Closing this support request.

**Closed by fasterit** 2024-01-15 20:23 UTC
Labels: documentation :open_book:, support request, Linux :penguin:
