### ISSUE TITLE
Temperature reporting in htop

### ISSUE THREAD

**Issue by MagicRB** [htop-dev/htop#52] opened 2020-08-31 19:11 UTC
I know htop is a system monitor, and not meant to read sensors, but it is useful to have all the temperature metrics right next to your core clocks and other metrics, especially for overclocking or trying not to burn your cpu

**Comment by eworm-de** [comment] 2020-09-02 13:48
This is a duplicate of #49, no?

**Comment by natoscott** [comment] 2020-09-03 06:49
Duplicate of 49

**Closed** 2020-09-03 06:50 UTC
