### ISSUE TITLE
Periodic ui hang when scrolling

### ISSUE THREAD

**Issue by TheJJ** [htop-dev/htop#467] opened 2021-01-11 13:01 UTC
This more an annoyance than an issue, but the "old" htop allowed smooth navigation and scrolling without any interruption. My current version 3.0.4 completely freezes for ~300ms when the information is gathered.

Maybe this update can be asynchronized :)

**Comment by BenBE** [comment] 2021-01-11 13:33
Which columns do you have activated? How many processes / threads are currently active in the system? Are you running with tree view active? Sorted by which column? Is display of userland/kernel threads active?

**Comment by TheJJ** [comment] 2021-01-11 14:02
131 processes. tree-view is on, sort by pid, no threads displayed. columns: pid, user, prio, nice, virt, res, shr, state, cpu, mem, time, disk_io_read, disk_io_write, command

**Comment by BenBE** [comment] 2021-01-11 14:55
Can you try to compile `htop` with debug information (`-gdwarf -fno-omit-frame-pointer`) and see if you can get a [flamegraph](https://github.com/brendangregg/FlameGraph) from running `htop` that way (please document the commit you used for building)?

To get the flamegraphs, once `htop` is build with debug information, run (as root, or otherwise privileged user):
```bash
perf record -Fmax -a --call-graph dwarf -- ./htop
perf script | ./../FlameGraph/stackcollapse-perf.pl | grep htop | ./../FlameGraph/flamegraph.pl > htop.performance.svg
```
**WARNING:** Produces a lot of data FAST.

Please also try to provide a baseline profile of the "old" htop version you used (which version was that?) for comparison. TIA.

Additionally trying to get some quantitative data from `strace` (for syscall latency) might also be worth a look.

**Comment by cgzones** [comment] 2021-01-11 16:19
Another contribution to this delay might be the header getting redrawn on every key press and a each draw causes the meters to gather its data.

#469 might help.

**Comment by cgzones** [comment] 2021-01-12 17:06
@TheJJ do you have CPU frequency enabled and by change using an AMD processor?
Does the delay go away when not showing the CPU frequency?

**Comment by TheJJ** [comment] 2021-01-12 17:11
Yes that's it! After disabling the frequency view, it no longer hangs yey :smiley_cat:

**Comment by cgzones** [comment] 2021-01-12 18:01
Duplicate of #471

**Closed by cgzones** 2021-01-12 18:01 UTC
Labels: bug :bug:, enhancement, question :grey_question:
